export default [
    {title:"Infosys Insta Award", description:"Won the Infosys Insta Award for setting up a benchmark performance at work", logo:"https://lh3.googleusercontent.com/dMOgHfY3m1TKIAMY7dKg2aOh8P3P5O47In66g_gW6fX5zxGdAdxFawriYyCQBM76AlOVa6gLQCD__2rDSx9gYQGbKQr6h23unDzyQTMyFvbHE4suVRMleWpePggZjTC20LMGezOvpw=w2400"},
    {title:"Udemy Certification", description:"Successfully completed my Udemy Certification on Full Stack web development through a course called Web developer bootcamp by Colt Steele. It was an intensive course which covers a wide range of web development technologies namely HTML5, CSS3,JS, JQuery, Node JS (Express), Mongo db etc. ",logo:"https://lh3.googleusercontent.com/pVf665a1UELvJje_0eBdHbvXbnDgAIRsfK_TKxN4Xo54V5OgvVFmATtlMmz-n8tiVQIHnHlnEtBEAIC2VqZJ2zq0Lm03ln2_vXCJiP1OJvsb_xlIWVT6Sls7ea-3EAHYTpNa7Y3_qw=w2400"},
    {title:"Infosys Certification", description:"Successfully completed my certification on Front end web development at Infosys",logo:"https://lh3.googleusercontent.com/dMOgHfY3m1TKIAMY7dKg2aOh8P3P5O47In66g_gW6fX5zxGdAdxFawriYyCQBM76AlOVa6gLQCD__2rDSx9gYQGbKQr6h23unDzyQTMyFvbHE4suVRMleWpePggZjTC20LMGezOvpw=w2400"},
    {title:"National Service Scheme", description:"Out of personal interest, I engaged myself in social work by serving in the National Service Scheme Cell for more than 2 years. With NSS, I actively participated in social awareness programs such as Road safety, Environmental awareness programs and several camping programs where we helped in revovating Government schools and hospitals",logo:"https://lh3.googleusercontent.com/3MBcKM4WFPAeERfy13AX5bvU7OAiYC79E4dIiY4edfsRNGXq1cmZUl-_QkSu95hyNY-SvxSs1QrOXMkQ8E_NyilrKAifvLnKTc3xLeR8WEcdouTuBj9eQ7-XWH1vwiSakJ8nRMcM1Q=w2400"},
    {title:"Infosys Athletics Club", description:"I am an active member of Infosys Athletic Club. I have participated in several runnng events (mini marathons) conducted by Infosys and other organizations and I have even won in a few of them",logo:"https://lh3.googleusercontent.com/dMOgHfY3m1TKIAMY7dKg2aOh8P3P5O47In66g_gW6fX5zxGdAdxFawriYyCQBM76AlOVa6gLQCD__2rDSx9gYQGbKQr6h23unDzyQTMyFvbHE4suVRMleWpePggZjTC20LMGezOvpw=w2400"},
    {title:"Emerge 2K17", description:"I organized the Editorial committee of 7th National Level Technical Symposium Emerge 2k17 during the academic year 2017-2018",logo:"https://lh3.googleusercontent.com/3MBcKM4WFPAeERfy13AX5bvU7OAiYC79E4dIiY4edfsRNGXq1cmZUl-_QkSu95hyNY-SvxSs1QrOXMkQ8E_NyilrKAifvLnKTc3xLeR8WEcdouTuBj9eQ7-XWH1vwiSakJ8nRMcM1Q=w2400"},
    {title:"Publications", description:"I did my project on 'Theft Detection using IOT in Automated Toll Plaza' and I published a journal on the same in the International Journal Of Advance Research and Development",logo:"https://lh3.googleusercontent.com/pVf665a1UELvJje_0eBdHbvXbnDgAIRsfK_TKxN4Xo54V5OgvVFmATtlMmz-n8tiVQIHnHlnEtBEAIC2VqZJ2zq0Lm03ln2_vXCJiP1OJvsb_xlIWVT6Sls7ea-3EAHYTpNa7Y3_qw=w2400"},
    {title:"Inplant trainings", description:"Undergone inplant training at Integral Coach Factory, Chennai in the year 2017",logo:"https://lh3.googleusercontent.com/pVf665a1UELvJje_0eBdHbvXbnDgAIRsfK_TKxN4Xo54V5OgvVFmATtlMmz-n8tiVQIHnHlnEtBEAIC2VqZJ2zq0Lm03ln2_vXCJiP1OJvsb_xlIWVT6Sls7ea-3EAHYTpNa7Y3_qw=w2400"},
    {title:"100 Kms Cycling", description:"I am an enthusiastic participant in long distance cycling events. I won 5th place in a hundred kilometers cycling event conducted by INCG",logo:"https://lh3.googleusercontent.com/oUFCFZTaQWL-s-pQoeHQUzSDHzvedGYdDdhtlzA0cy5dG5qqwgxSsIbwdwhm399WHIiftyUrK-0C0x3fQiKaVzE7dGcPzmvvZegsPHqzfOQYfRJeYHuuDqJ59DPcrnGRHV16uYkA7g=w2400"},
    {title:"Intra School Volleyball competition", description:"I am an enthusiastic participant in Intra school sports events. I am happy to be a part of the team that won the Intra School Volleyball competitions thrice",logo:"https://lh3.googleusercontent.com/oUFCFZTaQWL-s-pQoeHQUzSDHzvedGYdDdhtlzA0cy5dG5qqwgxSsIbwdwhm399WHIiftyUrK-0C0x3fQiKaVzE7dGcPzmvvZegsPHqzfOQYfRJeYHuuDqJ59DPcrnGRHV16uYkA7g=w2400"},
    
    ]