export default [
    
{projectName:"Infogram",shortDescription:"Hi there! I'm Infogram. Want to know about Arvind? I know everything. Check me out", projectDescription:"Infogram! a portfolio project. One place to find all my projects. The application's user interface is inspired from Instagram and Linked In. It is developed using React JS utilizing the Material UI library. App is available in two themes 'Light' and 'Dark'", projectThumbnail:"https://lh3.googleusercontent.com/Tqmbpov6-NvFAJ3CP32pp1VP0_zVYi7jAgmXLbrTE3XTcFWDZR5Da1L33TiG656eXfeXeQRQCeABPgCfVwaIKJerA5VKl80sLoiw_htS9gtITEGPFRwUD4PUFSothd0tUV0jTWMR2w=w2400", url:"https://infogram-portfolio.herokuapp.com/", githubUrl:"https://github.com/Akshark1075/Infogram",responsive:"Yes",compatibleDevices:"Desktops, Mobile"},
{projectName:"Super Mario",shortDescription:"Recreation of the classic Super Mario video Game. Relive your good old days!", projectDescription:"Relive the good old days of playing video games with friends. This project is a recreation of the classic Super Mario video Game developed using html5 Canvas and Vanilla Javascript", projectThumbnail:"https://lh3.googleusercontent.com/gYs8eNdfqiEESNvV6I-DTD7K0u5oP1mzkkFePXkcNCSYMrOkQNFGzY4qC8wPiFthJ5Igzt1F3y8So1JZEX9jAFidzDwqIDrNF12BI4_Pdi85CiK9l4egMenmY_CYPXhkQohMFxaK7w=w2400", url:"https://supermario-htmlcanvas.herokuapp.com/", githubUrl:"https://github.com/Akshark1075/Super-Mario",responsive:"No",compatibleDevices:"Desktops"},
{projectName:"RPU FC",shortDescription:"I'm a Fantasy league application created for RPU football club. Pick your team today! They score, you win!", projectDescription:"Ever played Premier League's Fantasy Premier League? RPU FC is a Fantasy league application created for RPU football club developed using HTML5, CSS3,JS, Node JS(Express), Mongo db. It was inspired from Premier League's FPL app. You need to pick a team of 11 players everyday. You will be awarded points based on the performance of the player selected in current day's game. The points of all the users will be tracked under the points table, which determines the winner of the month. The app uses a external db hosted on Mongo Atlas.",projectThumbnail:"https://lh3.googleusercontent.com/hrWMEipzUiktZ7gPo6XD0KlW-P5pAuiRm2gFRylo9lylfUopS94YFjEmUlYOeFbEu2fu-sjx7U3fCElcHRzZbs77G5e36nH9_kA-fwIdtdWtWMQx4L03fuh98SLkEvr_KOIat_FAVA=w2400", url:"https://realprinceunited.herokuapp.com/", githubUrl:"https://github.com/Akshark1075/RPU_FPL",responsive:"Yes",compatibleDevices:"Desktops, Mobile"},
{projectName:"Shades",shortDescription:"Looking for the perfect combination of colors for your application? Try Shades- Color Picker app", projectDescription:"Shades is a react based color picker app which allows you to create your own custom color palettes. You will be able to get rgb/ rgba/ hex color codes of a wide range of colors. The palettes created can be saved and revisited. You can also rearrange palettes in the homepage just by dragging and dropping",projectThumbnail:"https://lh3.googleusercontent.com/kmC3w4X-adELgEz6zwgiRK7t4tNnn1HdKlRjVktjT6F9wW4tApfQlq7ektB7ni802s4tpgplqmmlk9OyG6gt8W3p8aisy23lKtknfVJbea6VgNyGQ1c0nGNbVNzwMmoYYT835ghsfw=w2400", url:"https://shades-react-color-picker.herokuapp.com/", githubUrl:"https://github.com/Akshark1075/color-picker",responsive:"Yes",compatibleDevices:"Desktops, Mobile"},
{projectName:"D!rt2Shine",shortDescription:"A car wash app for booking your slot for door step car wash. Hurry! book your slot", projectDescription:"Dirt2Sh!ne is a web app for booking your slot for your door step car wash. It offers a wide range of wash packages to choose from. The app was developed as a freelance project (Currently not in use. Still under development). It was developed using HTML5, CSS3,JS, Node JS(Express), Mongo db. The app uses a external db hosted on Mongo Atlas",projectThumbnail:"https://lh3.googleusercontent.com/GcfVNSJ1IvfxQXGnWsl34v3fNFI2A0aNkhvmKg86L3AbHxkC5-71-pcB5JjQDVZ5dGog508U_MqjUGsgPYAlyPt_fIxNrTb7GMPk4z2_0aMaILGCAJobkbjP8kNMt402KVaNuDwrRA=w2400", url:"https://dirt2shine.herokuapp.com/", githubUrl:"https://github.com/Akshark1075/dirt2Shine",responsive:"Yes",compatibleDevices:"Desktops, Mobile"},
{projectName:"Lights Out",shortDescription:"Keep the lights out! An entertaing game app. Turn off the lights to win!", projectDescription:"Lights out is an interactive game app developed using react js. It consists of a 5 by 5 grid of lights. When the game starts, a random number of these lights is switched on. Pressing any of the lights will toggle it and the adjacent lights.",projectThumbnail:"https://lh3.googleusercontent.com/MwreB4TqRtSsoeMNi-MB6JIQgB9v7zILsi7ScBUtKDqUGxRMXBkkGKuj7Y07DIayqk90zxm4dyCe3uTNEXejUS6D1zd2O-e0di6uTWePtL5t2HCsUa3dKugeaMzes2ANnVM6n2jGUw=w2400", url:"https://lightsout-react.herokuapp.com/", githubUrl:"https://github.com/Akshark1075/Lights-Out_React",responsive:"No",compatibleDevices:"Desktops" },

{projectName:"Dad Jokes",shortDescription:"A funny app that makes you laugh out loud. It gives you a set of random 10 jokes on every click of the button", projectDescription:"Dad Jokes is react based app which gives you an extensive collection of bad jokes that dads are known for telling. App has an intriguing UI that allows you to upvote or downvote a joke implemented with the capability of data persistance .",projectThumbnail:"https://lh3.googleusercontent.com/ZKITb9ciRmKSnJPDFhoR_cGE5WGirNI8_woFNp9bNptwD2j3LQgKRiKO9dpOawMTvSiUuV_UtdftK5x-Gm649ysYH81DHUpvNeOUblH9shTCSxtMYduy_ASFYgQFI8MvUIcBioHrhg=w2400", url:"https://dadjokess.herokuapp.com/", githubUrl:"https://github.com/Akshark1075/dadJokes", responsive:"No",compatibleDevices:"Desktops"},
{projectName:"Yahtzee",shortDescription:"It's a dice game. Roll the dices and try your luck", projectDescription:"Yahtzee is a dice game similar to Poker. The objective of the game is to score points by rolling five dice to make certain combinations. The dice can be rolled up to three times in a turn to try to make various scoring combinations and dice must remain in the box. A game consists of thirteen rounds. After each round the player chooses which scoring category is to be used for that round. Once a category has been used in the game, it cannot be used again. The scoring categories have varying point values, some of which are fixed values and others for which the score depends on the value of the dice. A Yahtzee is five-of-a-kind and scores 50 points, the highest of any category. The winner is the player who scores the most points.",projectThumbnail:"https://lh3.googleusercontent.com/AzNn9MjUBLMivjle5OaujVtdyYRUyaclQW6wgrRqvaGyUj0D_-WCC3g70crxkIKRJsRXAcqAdWWrvshSoLxuUFTEwhXqxiRuJnuVSdqhY3B5TES_WAFqjrOxUCG7aFsU6MVzaCbSOA=w2400", url:"https://yahtzee-ak.herokuapp.com/", githubUrl:"https://github.com/Akshark1075/Yahtzee_React",responsive:"No",compatibleDevices:"Desktops"},
{projectName:"Hangman",shortDescription:"Hangman! a guessing game. You lose, he dies!", projectDescription:"Hangman is a guessing game. The app randomly picks a 5 letter word and you need to find it by suggesting letters within a certain number of guesses. Every wrong guess add a body part. You lose when you run out of guesses ",projectThumbnail:"https://lh3.googleusercontent.com/4KcCoWk-_fUfHUIrMtb-CRNWgwCXP8hZ-EmUUxYn2y82URL_fpJu3CTxR6CRrvJBSrllXlypBaIh83GdQrNuMxLPJmPDtgo6ltMkMq3aVva15-IP_x9_yTBmQPMf_AID2btzYLfNPw=w2400", url:"https://dashboard.heroku.com/apps/hang-man-react", githubUrl:"https://github.com/Akshark1075/Hangman_React",responsive:"Yes",compatibleDevices:"Desktops, Mobile" },
{projectName:"2048",shortDescription:"Join the tiles, get to 2048!", projectDescription:"2048 is  javascript based app played on a plain 4x4 grid, with numbered tiles that slide when a player moves them using the four arrow keys.Every turn, a new tile randomly appears in an empty spot on the board with a value of either 2 or 4. Tiles slide as far as possible in the chosen direction until they are stopped by either another tile or the edge of the grid. If two tiles of the same number collide while moving, they will merge into a tile with the total value of the two tiles that collided.",projectThumbnail:"https://lh3.googleusercontent.com/TCp27N22Zf9EtWpPYRBsqHpEXuaF-eI81NwJWWLx9WKVdxKBf7UuTqO5y5WPxLjaeNFXppOPjWhavDiw4rLT3nSarV4HPXttCrgk2hKAF81ud9jjpBwyv3BMz4B55PFnWoKibJ0izg=w2400", url:"https://two04eight.herokuapp.com/", githubUrl:"https://github.com/Akshark1075/2048-Game", responsive:"Yes",compatibleDevices:"Desktops, Mobile"},


{projectName:"Card Dealer",shortDescription:"Click the button and get a random card", projectDescription:"Card Dealer is a react based app that hands out a random card on every click of the button. The cards dealt are stacked over one another",projectThumbnail:"https://lh3.googleusercontent.com/Us6Cki1n7q2u0DWZM6MsNmqd2wMnc_vSgo4oCPsd5DxdP4UwGsjfJIlVQTNpZGQ2Z2lw36Sv_BZIRhkuKenEsEYIIzX4kx-lKTp64H2GvWkh1BZOtC4lZH4AEAdm6Sxd5Mj2VVr-VA=w2400",url:"https://card-dealer-react.herokuapp.com/", githubUrl:"https://github.com/Akshark1075/Card-Dealer_React", responsive:"Yes",compatibleDevices:"Desktops, Mobile"},
{projectName:"Color Boxes",shortDescription:"Click the boxes and get a random color", projectDescription:"Color Boxes is a react based interactive app. It consists of a grid of randomly colored boxes that changes color on every click. The new random color doesn't repeat the previously appeared color",projectThumbnail:"https://lh3.googleusercontent.com/enFPv3VElo-jQ0sv0aB2O9kQEElO6U0zuD1e529s7DSe103FiUKSHid7FMhGuyMclGLLZy0SnXZYjOy1VPetJYc3GMLhqRYoTCy3_D7GvTteKGSS5yPPnL236d8TPlHA7emVElrvRg=w2400", url:"https://color-boxes-ak.herokuapp.com/", githubUrl:"https://github.com/Akshark1075/Color_Boxes_React",responsive:"Yes",compatibleDevices:"Desktops, Mobile"},
{projectName:"RPU Auction",shortDescription:"Pick your teams by conducting auction", projectDescription:"It is an Auction application created for RPU football club. It is created for conducting an auction between 3 users for picking up 3 random teams",projectThumbnail:"https://lh3.googleusercontent.com/dOzf1eqwRCWE8v1dB7hQfDTL-rE3jur1vZLGYNlNur7e1I4SAEDv7ZW4GnTsuVIXEF0c7DV7B4cL0KZZEoi-IMPxwz_ZVms5BQt6iskKkHiUcMv-yOMKfL_vAVs5Ys9JJFQIpi5SdQ=w2400", url:"https://rpu-auction.herokuapp.com/", githubUrl:"https://github.com/Akshark1075/RPU-Auction",responsive:"No",compatibleDevices:"Desktops" },
{projectName:"Pokedex",shortDescription:"A simple Pokemon dictionary", projectDescription:"A simple react app that displays the types of Pokemons and their powers",projectThumbnail:"https://lh3.googleusercontent.com/6ElA5qs5OUQwtWFDms09E_Id4yZ6NW-jcANCvbQzli7B3ytBS4qQQux8NjnSSW34tGGazeXtab133t_VfQica7cFix03eb14ruoiiau-LzWyeKipM9ATG8eP-VmGYdPwvtc8afiSSg=w2400", url:"https://pokemon-pokedex-ak.herokuapp.com/", githubUrl:"https://github.com/Akshark1075/Pokedex_React", responsive:"No",compatibleDevices:"Desktops"},
{projectName:"Roll Dice",shortDescription:"Roll the dices and try your luck", projectDescription:"A simple react app that allows you to roll dices on a button click with a bit of CSS Animation.",projectThumbnail:"https://lh3.googleusercontent.com/w95i1pFFEGOJVHM3Ad4HDRRYBniqx5eDiZKo275qEu2Ju17_ro8QKj4qGQ-wKBGkAnWGuYpVTf4q30pBOODMkPR59nkVzxxfzmKjOxxx4yXRcG165E5Y0pV6CMxYz8PSBn-zdbstuA=w2400", url:"https://roll-dice-ak.herokuapp.com/", githubUrl:"https://github.com/Akshark1075/Roll-Dice_React", responsive:"No",compatibleDevices:"Desktops"},

]
function testImage(URL,callback) {
    var tester=new Image();
   tester.onload=()=>{callback(URL)};
   tester.onerror=()=>{callback("")};
   tester.src=URL
}


function callback(result){
    alert(result)
    return result
}
